### ISSUE TITLE
Is dependency on TabExpension++ still needed

### ISSUE THREAD

**Issue by vors** [pcgeek86/azure-powershell-extensions#1]
Couple things
-  TabExpansionPlusPlus is the [newer version](https://github.com/lzybkr/TabExpansionPlusPlus#tabexpansionplusplus) of the module. It's available in PSGallery. This dependency can be pulled in with gallery dependency mechanism.
-  In PowerShell v5 cmdlet `Register-ArgumentCompleter` is part of `Microsoft.PowerShell.Core`.

With the former, maybe external dependency can be completely avoided?

**Comment by pcgeek86** [comment]
@vors I can take a look at it, but it may not be immediate. :) Thanks for the heads up!

**Comment by pcgeek86** [comment]
@vors I've removed the dependency from the module, and the argument completers use the built-in PowerShell v5 command. Thanks for the recommendation!

https://github.com/pcgeek86/azure-powershell-extensions/commit/b3889ebe9b5ca85c596494021828917fae555a64
